### ISSUE TITLE
Getting Error using Supabase Db

### ISSUE THREAD

**Issue by its-aomi** [auryn31/plant-watering#1]
Tried using supabase for db but getting this error. How am i supposed to install the project correctly on vercel, the readme file provides very little info.

**Comment by its-aomi** [comment]
`VercelPostgresError: VercelPostgresError - 'invalid_connection_string': This connection string is meant to be used with a direct connection. Make sure to use a pooled connection string or try `createClient()` instead.
    at createPool (webpack-internal:///(rsc)/./node_modules/@vercel/postgres/dist/chunk-WDBQYBZQ.js:178:11)
    at createKysely (webpack-internal:///(rsc)/./node_modules/@vercel/postgres-kysely/dist/index.js:92:73)
    at eval (webpack-internal:///(rsc)/./src/app/db/token.ts:17:81)
    at (rsc)/./src/app/db/token.ts (E:\plant\plant-watering\.next\server\app\page.js:484:1)
    at __webpack_require__ (E:\plant\plant-watering\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/page.tsx:13:67)
    at (rsc)/./src/app/page.tsx (E:\plant\plant-watering\.next\server\app\page.js:506:1)
    at Function.__webpack_require__ (E:\plant\plant-watering\.next\server\webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:537:9)
    at process.processTimers (node:internal/timers:511:7)
    at async eB (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:401143)
    at async tt (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:404857)
    at async tr (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405407)
    at async tr (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405538)
    at async tl (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2057)
    at async E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2596 {
  digest: '1309231197'
}
 ⨯ node_modules\@vercel\postgres\dist\chunk-WDBQYBZQ.js (166:0) @ createPool
 ⨯ VercelPostgresError: VercelPostgresError - 'invalid_connection_string': This connection string is meant to be used with a direct connection. Make sure to use a pooled connection string or try `createClient()` instead.
    at createPool (webpack-internal:///(rsc)/./node_modules/@vercel/postgres/dist/chunk-WDBQYBZQ.js:178:11)
    at createKysely (webpack-internal:///(rsc)/./node_modules/@vercel/postgres-kysely/dist/index.js:92:73)
    at eval (webpack-internal:///(rsc)/./src/app/db/token.ts:17:81)
    at (rsc)/./src/app/db/token.ts (E:\plant\plant-watering\.next\server\app\page.js:484:1)
    at __webpack_require__ (E:\plant\plant-watering\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/app/page.tsx:13:67)
    at (rsc)/./src/app/page.tsx (E:\plant\plant-watering\.next\server\app\page.js:506:1)
    at Function.__webpack_require__ (E:\plant\plant-watering\.next\server\webpack-runtime.js:33:43)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:537:9)
    at process.processTimers (node:internal/timers:511:7)
    at async eB (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:401143)
    at async tt (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:404857)
    at async tr (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405407)
    at async tr (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:405538)
    at async tl (E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2057)
    at async E:\plant\plant-watering\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2596 {
  digest: '1309231197',
  page: '/'
}`

**Comment by auryn31** [comment]
you need to set your own env variables :)
You cannot just use mine :P
